# Generated by Django 5.1.7 on 2025-05-18 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khach', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('so_dien_thoai', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('dia_chi', models.TextField(verbose_name='Địa chỉ')),
            ],
        ),
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=100, verbose_name='Tên loại sản phẩm')),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dat', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt hàng')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantri.khachhang', verbose_name='Khách hàng')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('mo_ta', models.TextField(verbose_name='Mô tả sản phẩm')),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá bán')),
                ('so_luong', models.PositiveIntegerField(verbose_name='Số lượng trong kho')),
                ('hinh_anh', models.CharField(blank=True, max_length=255, null=True)),
                ('loai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantri.loaisanpham', verbose_name='Loại sản phẩm')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='quantri.donhang', verbose_name='Đơn hàng')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantri.sanpham', verbose_name='Sản phẩm')),
            ],
        ),
    ]
