# Generated by Django 5.1.7 on 2025-05-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenTK', models.CharField(max_length=30)),
                ('matKhau', models.CharField(max_length=50)),
                ('hoTen', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='loai',
        ),
        migrations.DeleteModel(
            name='LoaiSanPham',
        ),
    ]
